# Generated by Django 2.2.6 on 2022-09-29 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualityapp', '0007_auto_20220929_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreDefineExceptionProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PreDefineExceptionSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_status', models.CharField(choices=[('in_coming', 'In coming'), ('put_to_customer', 'Put to customer')], max_length=100, null=True)),
                ('order_status', models.CharField(max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('put_to_customer_date', models.DateTimeField(blank=True, null=True)),
                ('exp_resolve_date', models.DateTimeField(blank=True, null=True)),
                ('is_confirm_used', models.BooleanField(default=False)),
                ('is_modify_used', models.BooleanField(default=False)),
                ('is_cancel_used', models.BooleanField(default=False)),
                ('is_remark_used', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qualityapp.Order')),
                ('pre_define_problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='qualityapp.PreDefineExceptionProblem')),
                ('pre_define_solution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='qualityapp.PreDefineExceptionSolution')),
            ],
        ),
    ]
